package com.pallavi.loan.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a customer entity in the enterprise loan management system.
 *
 * This class encapsulates customer information including personal details
 * and contact information. It is mapped to the "customers" table in the database.
 */
@Entity
@Table(name = "customers")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Customer {

    /**
     * The unique identifier for the customer.
     * This is auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The first name of the customer.
     */
    private String firstName;

    /**
     * The last name of the customer.
     */
    private String lastName;

    /**
     * The email address of the customer.
     */
    private String email;

    /**
     * The phone number of the customer.
     */
    private String phoneNumber;

}
